### ISSUE TITLE
Features for Combat Tracker

### ISSUE THREAD

**Issue by jamesw98** [jamesw98/dnd-utils#7]
- [ ] Fixed Initiative 
- [ ] Fixed Damage
- [ ] Saving Throws
- [ ] Attack History
- [ ] Ability to Replay Attacks (reroll with the same input)
- [ ] Ability to Name Attacks
- [ ] Put creatures with 0 hit points at the bottom of the list
